sudo: required
services:
  - docker
before_install:
  - docker pull lineageos/android_build
before_script:
- cd $HOME && mkdir twrp
- wget -q https://github.com/TwrpBuilder/twrp-sources/releases/download/omni_twrp-7.1.2-20180326-norepo/omni_twrp-7.1.2-20180326-norepo.tar.xz
  -O $HOME/twrp.tar.xz
- tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:
  - cd $HOME/twrp/ && git clone https://github.com/ALGPHELLO/android_device_honor_AUM-L29.git device/honor/AUML29
  - git clone https://github.com/TwrpBuilder/android_device_generic_twrpbuilder.git device/generic/twrpbuilder
  - rm -rf bootable/recovery && git clone https://github.com/omnirom/android_bootable_recovery.git bootable/recovery
  - |
    docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/home/twrp/:rw,z" yshalsager/lineageos:14.1 bash << EOF
    cd /home/twrp/
    source build/envsetup.sh && lunch omni_AUML29-eng && make -j32 recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/AUML29/recovery.img $HOME/twrp/TWRP-$version-AUML29-$(date +"%Y%m%d").img

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$image"
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: ALGPHELLO/android_device_honor_AUM-L29
    branch: master

branches:
  except:
    - /^(?i:untagged)-.*$/
