sudo: required
services:
  - docker
before_install:
  - docker pull surendrajat/twrp-builder:latest
before_script:
- cd $HOME && mkdir twrp
- wget -q https://basketbuild.com/uploads/devs/yshalsager/CAS/twrp/omni_twrp-8.1-20180221-norepo.tar.xz
  -O $HOME/twrp.tar.xz
- tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:
  - cd $HOME/twrp/ && git clone https://github.com/ALGPHELLO/android_device_honor_AUM-L29.git device/honor/AUML29
  - rm -rf prebuilts/clang/host/linux-x86 && git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 prebuilts/clang/host/linux-x86 -b android-7.0.0_r21 --depth=1
  - git clone https://github.com/TwrpBuilder/android_device_generic_twrpbuilder.git device/generic/twrpbuilder
  - git clone https://github.com/omnirom/android_bootable_recovery.git bootable/recovery --depth=1
  - |
    docker run --rm -i -v "$(pwd):/root/twrp/:rw,z" surendrajat/twrp-builder bash << EOF
    cd /home/twrp/
    source build/envsetup.sh && lunch omni_AUML29-eng && make -j32 recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/AUML29/recovery.img $HOME/twrp/TWRP-$version-AUML29-$(date +"%Y%m%d").img

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$image"
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: ALGPHELLO/android_device_honor_AUM-L29
    branch: master

branches:
  except:
    - /^(?i:untagged)-.*$/
